### ISSUE TITLE
Docker deployment: UI works but "Run All Models" not triggering + auto-processing without click

### ISSUE THREAD

**Issue by JoaZ94** [yfde/Anymate#5]
# Description:

Hello, first of all thank you for sharing this project and for the detailed README.
I have successfully created a Docker image from this repository, following the installation and usage steps described in the README.

Here are the main details of my setup and the issues encountered:

#Summary (first paragraph of the issue):

Successfully built and ran the project in Docker (CUDA base, GPU enabled in Compose). The UI loads, .glb model uploads fine, and "Load All Models" shows as loaded — but clicking "Run All Models" produces no action. Additionally, after uploading a model, all three outputs start processing automatically without clicking the previous steps. GPU is not being used, and no logs are output from the container.

# Environment
Base image in Dockerfile: nvidia/cuda:12.2.0-base-ubuntu22.04

Purpose: Running only for rig inference (no training).

Docker Compose: Configured with GPU support (runtime: nvidia).

Host GPU: NVIDIA GPU with supported drivers installed.

Framework version: As per repository’s environment.yaml.

# Steps to Reproduce

Build the Docker image using the base image above.

Start the container via docker-compose up.

Access the web UI (Gradio) through the exposed port.

Upload a .glb 3D model.

Click "Load All Models" — UI shows that the models load successfully.

Click "Run All Models" — nothing happens, no visible processing or output updates.

# Observed Issues

Unexpected Auto-Processing

After uploading the .glb model, the application starts processing the three outputs automatically, even if the previous steps (e.g., “Load All Models”) have not been clicked.

"Run All Models" has no effect

Clicking this button produces no visible change or output in the UI.

No GPU usage detected

Despite the image being based on an NVIDIA CUDA base and Docker Compose specifying GPU runtime, the process runs entirely on CPU.

No logs from container

The running container does not produce logs (stdout/stderr) even when enabling PYTHONUNBUFFERED=1 or running in debug mode, making it hard to diagnose what’s happening.

# Expected Behavior

The processing steps should occur only when the respective buttons are clicked, in the intended order.

Clicking "Run All Models" should trigger the rig inference and show the results in the UI.

GPU acceleration should be used when available and configured.

The container should output logs for better debugging.

# Additional Context

Only inference functionality is being tested.

No manual changes were made to repository files except adjustments in the Dockerfile to allow external access to the Gradio UI (server_name="0.0.0.0").

If you need, I can provide my Dockerfile and docker-compose.yml for reproduction.

Thank you in advance for your time and for this great tool!
I’d be happy to help test any fixes or provide more environment details if needed.

**Comment by yfde** [comment]
Hi, thank you for bringing up the issue. We haven't tested this project with Docker. It would be helpful if you can provide your Dockerfile and docker-compose.yml so that I can try to reproduce the issue on my side.

**Comment by JoaZ94** [comment]
Hi, Thank you for addressing my issue.

The bpy==4.0.0 library was removed from the Dockerfile because it generated an error, and I don't think I need it to make the estimate. I also tried the bpy==4.4.0 version, but that didn't work either.

I look forward to any comments. Have a nice day.

[ContainerFiles.zip](https://github.com/user-attachments/files/21693420/ContainerFiles.zip)

**Comment by yfde** [comment]
Hi, thank you for providing the files.
I successfully ran the project with Docker, and the Web UI functions as expected.

I made the following minor changes:
1. bpy library: it was removed from PyPI, so I added an extra-index-url to the environment.yaml in this repo. The pip error is solved, so I deleted the line that removes bpy "RUN sed -i '/bpy==/d' environment.yaml"
2. Added "libxi6 libxkbcommon0 libgomp1" to apt-get install, which are required by bpy.
3. Deleted "runtime: nvidia". Specifying deploy.resources.reservations.devices is sufficient to enable GPU usage.

The rest of the Dockerfile and docker-compose.yml remain exactly the same. The web UI works well, and I cannot reproduce the issues you mentioned on my end. Please check your machine configuration, as everything works properly on my machine. There might be some host system differences causing the problems you're experiencing.

**Comment by JoaZ94** [comment]
Good evening.
I applied the suggested changes. I load the glb file, then click on “Load all models” and finally click on “Run All Models,” but nothing happens.

The three windows below start processing as soon as I load the file and, apparently, they don't finish.

<img width="1912" height="954" alt="Image" src="https://github.com/user-attachments/assets/99ec8ba9-33a3-4c52-b94b-01bc02ea0e43" />

**Comment by yfde** [comment]
Based on the screenshot, it appears to be stuck at running "os.system(f"python Convert.py --path {abs_path}")" to convert glb to obj. This step uses CPU and is typically fast, so it's normal that there wasn't any GPU usage.

The issue might be caused by spaces in the 'abs_path', so I've updated the code in this repo to add quotes around the abs_path. Please give it a try now. Also, please make sure bpy is installed following the steps mentioned in my previous comment.

**Comment by JoaZ94** [comment]
Hello,

First of all, thank you for sharing this project — your work is greatly appreciated.
Your recommendations worked for me, and I was able to get everything running.

I have a couple of questions regarding the scope of the repository:

Does the model only perform rigging, or does it also include skinning?

After the rigging (and skinning, if applicable), can the user generate any animations they want?

Thanks in advance for your time and clarification!

Best regards.

**Comment by yfde** [comment]
The model performs rigging and skinning.

We load the rig and skinning results from the model into a Blender file. Users can create any animations they want by modifying the skeleton's pose and adding keyframe poses in Blender.
